version: '3.8'
services:
  app:
    image: node:18

    environment:
     - DEBUG=app:*

    tty: true

    ports:
      - '3000:3000'

    volumes:
      - type: bind
        source: ./src/
        target: /app
    
    working_dir: /app

    command: npm start
